unexmin:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  spinning_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: spinning_joint
    pid: {p: 10.0, i: 0.01, d: 10.0}
  sphere_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sphere_joint
    pid: {p: 10.0, i: 0.01, d: 10.0}
